# Generated by Django 5.0.1 on 2025-10-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_usercompanymembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='usercompanymembership',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='usercompanymembership',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usercompanymembership',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
        migrations.AlterField(
            model_name='usercompanymembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
