# Netlify configuration for ERP Marocaine Frontend
[build]
  # Build command
  command = "cd frontend && npm ci && npm run build"
  
  # Directory to publish (relative to repo root)
  publish = "frontend/dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Production context (main branch)
[context.production]
  command = "cd frontend && npm ci && npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"
    VITE_API_URL = "https://your-backend-api.herokuapp.com"

# Deploy preview context (pull requests)
[context.deploy-preview]
  command = "cd frontend && npm ci && npm run build"
  
  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    VITE_API_URL = "https://your-staging-backend-api.herokuapp.com"

# Branch deploy context (other branches)
[context.branch-deploy]
  command = "cd frontend && npm ci && npm run build"

# Redirects for Single Page Application (SPA)
# This ensures that all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API proxy redirects (optional - if you want to proxy API calls through Netlify)
# Uncomment and configure if needed
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-api.herokuapp.com/api/:splat"
#   status = 200
#   force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"

# Build plugins (optional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Form handling (if using Netlify Forms)
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true

# Edge functions (if needed)
# [[edge_functions]]
#   function = "hello"
#   path = "/api/hello"
