# Generated by Django 5.0.1 on 2025-10-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0001_initial'),
        ('tax_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='tax_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax_engine.taxprofile', verbose_name='tax profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tax_engine.taxprofile', verbose_name='tax profile'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='catalog.unitofmeasure', verbose_name='base unit'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='catalog.unitofmeasure', verbose_name='purchase unit of measure'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unitofmeasure', verbose_name='unit of measure'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.unitofmeasure', verbose_name='purchase unit of measure'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='uom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.unitofmeasure', verbose_name='unit of measure'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'is_active'], name='catalog_cat_company_8bb58c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent__5307be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['company', 'type', 'is_active'], name='catalog_uni_company_4650fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('company', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='catalog_pro_company_5de2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'product_type'], name='catalog_pro_company_d3aa28_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['internal_reference'], name='catalog_pro_interna_cf3095_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='catalog_pro_barcode_58f8f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'internal_reference')},
        ),
    ]
