# Generated by Django 5.0.1 on 2025-10-05 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('QUOTE', 'Quote'), ('SALES_ORDER', 'Sales Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('GOODS_RECEIPT', 'Goods Receipt Note'), ('DELIVERY', 'Delivery Note'), ('RETURN', 'Return Note'), ('ADJUSTMENT', 'Stock Adjustment'), ('TRANSFER', 'Stock Transfer')], max_length=20, verbose_name='document type')),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year for this sequence', verbose_name='fiscal year')),
                ('last_number', models.PositiveIntegerField(default=0, help_text='Last generated number in sequence', verbose_name='last number')),
                ('pattern', models.CharField(default='{PREFIX}-{YYYY}-{NNNN}', help_text='Pattern for generating numbers. Use {PREFIX}, {YYYY}, {MM}, {NNNN}', max_length=50, verbose_name='number pattern')),
                ('prefix', models.CharField(blank=True, help_text='Prefix for document numbers', max_length=10, verbose_name='prefix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
            },
        ),
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('formatted_number', models.CharField(max_length=100, verbose_name='formatted number')),
                ('document_type', models.CharField(max_length=20, verbose_name='document type')),
                ('document_id', models.PositiveIntegerField(verbose_name='document ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_numbers', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_numbers', to='sequences.documentsequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Document Number',
                'verbose_name_plural': 'Document Numbers',
            },
        ),
        migrations.AddIndex(
            model_name='documentsequence',
            index=models.Index(fields=['company', 'document_type', 'fiscal_year'], name='sequences_d_company_fddc70_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsequence',
            index=models.Index(fields=['company', 'is_active'], name='sequences_d_company_21a19e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together={('company', 'document_type', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['document_type', 'document_id'], name='sequences_d_documen_417a97_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['formatted_number'], name='sequences_d_formatt_025872_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['generated_at'], name='sequences_d_generat_64d7ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentnumber',
            unique_together={('sequence', 'number')},
        ),
    ]
