# Generated by Django 5.0.1 on 2025-10-05 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('companies', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WEIGHTED_AVG', 'Weighted Average'), ('STANDARD', 'Standard Cost'), ('MOVING_AVG', 'Moving Average')], default='WEIGHTED_AVG', max_length=20)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_valuations', to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_valuations', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_valuations', to='catalog.product')),
                ('stock_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='inventory.stockmove')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_valuations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_valuation',
                'ordering': ['-valuation_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'product', 'warehouse'], name='inventory_s_company_ffc649_idx'), models.Index(fields=['valuation_date'], name='inventory_s_valuati_36cb56_idx'), models.Index(fields=['valuation_method'], name='inventory_s_valuati_3fbdb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockValuationLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_valuation_layers', to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='catalog.product')),
                ('source_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='inventory.stockmove')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_valuation_layer',
                'ordering': ['layer_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'product', 'warehouse'], name='inventory_s_company_2df59c_idx'), models.Index(fields=['layer_date'], name='inventory_s_layer_d_eec80b_idx'), models.Index(fields=['is_exhausted'], name='inventory_s_is_exha_bca333_idx')],
            },
        ),
    ]
