# Generated by Django 5.0.1 on 2025-10-05 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='legal name')),
                ('ice', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='ICE must be exactly 15 digits', regex='^\\d{15}$')], verbose_name="ICE (Identifiant Commun de l'Entreprise)")),
                ('if_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='IF must be 7 or 8 digits', regex='^\\d{7,8}$')], verbose_name='IF (Identifiant Fiscal)')),
                ('rc', models.CharField(blank=True, help_text='Commercial register number', max_length=20, verbose_name='RC (Registre de Commerce)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='fax')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address_line1', models.CharField(max_length=200, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('country', models.CharField(default='Maroc', max_length=100, verbose_name='country')),
                ('currency', models.CharField(choices=[('MAD', 'Dirham Marocain (MAD)'), ('EUR', 'Euro (EUR)'), ('USD', 'US Dollar (USD)')], default='MAD', max_length=3, verbose_name='base currency')),
                ('locale', models.CharField(choices=[('fr-MA', 'Français (Maroc)'), ('ar-MA', 'العربية (المغرب)'), ('en-US', 'English (US)')], default='fr-MA', max_length=10, verbose_name='locale')),
                ('fiscal_year_start_month', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')], default=1, verbose_name='fiscal year start month')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='VAT number')),
                ('tax_rounding_method', models.CharField(choices=[('ROUND_HALF_UP', 'Round Half Up'), ('ROUND_HALF_DOWN', 'Round Half Down'), ('ROUND_UP', 'Round Up'), ('ROUND_DOWN', 'Round Down')], default='ROUND_HALF_UP', max_length=20, verbose_name='tax rounding method')),
                ('inclusive_taxes', models.BooleanField(default=False, help_text='Whether prices include taxes by default', verbose_name='inclusive taxes')),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/', verbose_name='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='invoice prefix')),
                ('quote_prefix', models.CharField(default='QUO', max_length=10, verbose_name='quote prefix')),
                ('po_prefix', models.CharField(default='PO', max_length=10, verbose_name='purchase order prefix')),
                ('so_prefix', models.CharField(default='SO', max_length=10, verbose_name='sales order prefix')),
                ('default_payment_terms', models.IntegerField(default=30, verbose_name='default payment terms (days)')),
                ('default_quote_validity', models.IntegerField(default=30, verbose_name='default quote validity (days)')),
                ('email_signature', models.TextField(blank=True, verbose_name='email signature')),
                ('default_costing_method', models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WAC', 'Weighted Average Cost')], default='FIFO', max_length=10, verbose_name='default costing method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
